// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	permissionFieldNames          = builder.RawFieldNames(&Permission{})
	permissionRows                = strings.Join(permissionFieldNames, ",")
	permissionRowsExpectAutoSet   = strings.Join(stringx.Remove(permissionFieldNames, "`auto_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	permissionRowsWithPlaceHolder = strings.Join(stringx.Remove(permissionFieldNames, "`auto_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePermissionAutoIdPrefix = "cache:permission:autoId:"
)

type (
	permissionModel interface {
		Insert(ctx context.Context, data *Permission) (sql.Result, error)
		FindOne(ctx context.Context, autoId int64) (*Permission, error)
		Update(ctx context.Context, data *Permission) error
		Delete(ctx context.Context, autoId int64) error
	}

	defaultPermissionModel struct {
		sqlc.CachedConn
		table string
	}

	Permission struct {
		AutoId         int64        `db:"auto_id"`         // 权限ID
		PermissionName string       `db:"permission_name"` // 权限名称
		PermissionUrl  string       `db:"permission_url"`  // 访问路径
		IsDeleted      int64        `db:"is_deleted"`      // 软删除
		CreatedAt      time.Time    `db:"created_at"`      // 创建时间
		UpdatedAt      time.Time    `db:"updated_at"`      // 更新时间
		DeletedAt      sql.NullTime `db:"deleted_at"`      // 删除时间
	}
)

func newPermissionModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPermissionModel {
	return &defaultPermissionModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`permission`",
	}
}

func (m *defaultPermissionModel) Delete(ctx context.Context, autoId int64) error {
	permissionAutoIdKey := fmt.Sprintf("%s%v", cachePermissionAutoIdPrefix, autoId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `auto_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, autoId)
	}, permissionAutoIdKey)
	return err
}

func (m *defaultPermissionModel) FindOne(ctx context.Context, autoId int64) (*Permission, error) {
	permissionAutoIdKey := fmt.Sprintf("%s%v", cachePermissionAutoIdPrefix, autoId)
	var resp Permission
	err := m.QueryRowCtx(ctx, &resp, permissionAutoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `auto_id` = ? limit 1", permissionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, autoId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionModel) Insert(ctx context.Context, data *Permission) (sql.Result, error) {
	permissionAutoIdKey := fmt.Sprintf("%s%v", cachePermissionAutoIdPrefix, data.AutoId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, permissionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PermissionName, data.PermissionUrl, data.IsDeleted, data.DeletedAt)
	}, permissionAutoIdKey)
	return ret, err
}

func (m *defaultPermissionModel) Update(ctx context.Context, data *Permission) error {
	permissionAutoIdKey := fmt.Sprintf("%s%v", cachePermissionAutoIdPrefix, data.AutoId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `auto_id` = ?", m.table, permissionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PermissionName, data.PermissionUrl, data.IsDeleted, data.DeletedAt, data.AutoId)
	}, permissionAutoIdKey)
	return err
}

func (m *defaultPermissionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePermissionAutoIdPrefix, primary)
}

func (m *defaultPermissionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `auto_id` = ? limit 1", permissionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPermissionModel) tableName() string {
	return m.table
}
